facebook:
  key: '315783835195742'
  secret: '979acddccb558815e0e06c73ce1d3f0c'
twitter:
  key: 'aIge6ADDxeRLL0D0DfNiA'
  secret: 'WZr5DPDmLNJK1JGEaStArnCki0Rau8yS3mZInpBSh0'
google:
  key: '522182871512.apps.googleusercontent.com'
  secret: '5W90m4arBoUwAHxGNiPIJBjq'
