application:
  host: 'potee.me'
  hosts:
    - potee.me
    - potee.ru
    - 3007.vkontraste.ru
    - stage.potee.ru
    - localhost
facebook:
  key: 
  secret:
twitter:
  key:
  secret:
google:
  key:
  secret:
